// <auto-generated />
using System;
using ASP_ICMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_ICMS.Migrations
{
    [DbContext(typeof(ASP_ICMSContext))]
    [Migration("20250530012101_KantorChange250530")]
    partial class KantorChange250530
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_ICMS.Models.ChoiceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChoiceList");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("SOPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOPName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("SOPMaster");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMasterAuditType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SOPAuditTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SOPMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SOPAuditTypeId");

                    b.HasIndex("SOPMasterId");

                    b.ToTable("SOPMasterAuditType");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMasterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<int>("SOPMasterId")
                        .HasColumnType("int");

                    b.Property<int>("SOPTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SOPMasterId");

                    b.HasIndex("SOPTypeId");

                    b.ToTable("SOPMasterType");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMaster", b =>
                {
                    b.HasOne("ASP_ICMS.Models.ChoiceList", "Division")
                        .WithMany("SOPMasters")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMasterAuditType", b =>
                {
                    b.HasOne("ASP_ICMS.Models.ChoiceList", "SOPAuditType")
                        .WithMany("SOPAuditTypes")
                        .HasForeignKey("SOPAuditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASP_ICMS.Models.SOPMaster", "SOPMaster")
                        .WithMany("AuditTypes")
                        .HasForeignKey("SOPMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SOPAuditType");

                    b.Navigation("SOPMaster");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMasterType", b =>
                {
                    b.HasOne("ASP_ICMS.Models.SOPMaster", "SOPMaster")
                        .WithMany("SOPTypes")
                        .HasForeignKey("SOPMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_ICMS.Models.ChoiceList", "SOPType")
                        .WithMany("SOPTypes")
                        .HasForeignKey("SOPTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SOPMaster");

                    b.Navigation("SOPType");
                });

            modelBuilder.Entity("ASP_ICMS.Models.ChoiceList", b =>
                {
                    b.Navigation("SOPAuditTypes");

                    b.Navigation("SOPMasters");

                    b.Navigation("SOPTypes");
                });

            modelBuilder.Entity("ASP_ICMS.Models.SOPMaster", b =>
                {
                    b.Navigation("AuditTypes");

                    b.Navigation("SOPTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
